# In order to install old Rubies, we need to use old Ubuntu distibution.
dist: trusty
language: ruby
script: "script/test_all"
email: false
before_install:
  - script/update_rubygems_and_install_bundler
bundler_args: "--standalone --binstubs --without documentation"
rvm:
  - 2.6.6
  - truffleruby
  - truffleruby-head
